### ISSUE TITLE
Database import hint

### ISSUE THREAD

**Issue by formicant** [lipu-linku/lipu-linku.github.io#6]
There’s a hint in the [jasima Linku](https://lipu-linku.github.io/about/jasima/) page:
> To import the database on your website, use:
> ```html
> <script src="https://lipu-linku.github.io/jasima/data.json"></script>
> ```

How am I supposed to use this on my site?

As far as I understand, in order to do something useful with the json, I have to load it from javascript like that:
```javascript
const response = await fetch('https://lipu-linku.github.io/jasima/data.json');
const json = await response.json();
// do something with `json`
```

Am I wrong?

**Comment by AcipenserSturio** [comment]
Sorry, you're entirely correct. I was writing the about page off my memory and wrote something that just entirely doesn't work but I had convinced myself that it does. jan Kekan San or I will fix the about page later.

**Comment by formicant** [comment]
Now, the hint says:
```
const bundle = JSON.parse(Get("https://lipu-linku.github.io/jasima/data.json"))
```

It uses the `Get` function defined in https://lipu-linku.github.io/scripts.js

This one-liner won’t work on other sites without referencing your js file or adding the definition of `Get` manually.
